# We opt to use https://supabase.com/ for our dev platform, it uses postgres
# See the following resources for details:
# streamlit info: https://docs.streamlit.io/develop/tutorials/databases/supabase
# supabase Auth: https://supabase.com/docs/guides/auth

SUPABASE_KEY = "xxx"
SUPABASE_URL = "xxx"